language: ruby
rvm:
- 2.4
install:
- gem install jekyll
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_e918b92733bd_key -iv $encrypted_e918b92733bd_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
