language: ruby
rvm:
- 2.4
install:
- gem install jekyll
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: iSZhdVEzSk9wSgbo42zQm7I5ynWwyWiK2WqkcrsVbJDeUbVeUfjp5Ne7oWIOsE7WfJCvky13e+VQxhZy336wlvyLmiD3gj89cbQJjztAyRzRsvprCnGfBAJniNAUW8Y3014IHmtzLSerA89YT+vk+OCycnWRob+Vk9FvRNX5jrvBby9XuDFN4SttJ+AO4870MqBE43E6VfoYd5y0xxVVTXej5q1nrKyfrc9vUZRIbmCZ2qH4SeimCG/0rc86KPSTxXociQz4ysDWA7rWG3nIOZ2mqaLvhYuPKYHB1pRk1GVpAlG+HGFxCsXBrzecAUYdjAOVRcyYyAUvpMc2pAkWoFaegXF6xWkzrdcHJYhlDS9xdCOBH2+jOIwwmxjvdyjobrFcxU4IjNRENBrxlSCwnMGAo2+odm4oMGjLDa8TyZoi8yirlJ3WDiwqZhCoxqYWRZjbzkjO07qTp13oVkkLr4iWg6D6K5P9oIqYusiWCXE+xE/0fPyrbTOAsueW6EwHGDnyPhTSOT42ZGAn/Qg7cPe+Sk+YSH6lTgytor/mhhFQejAN+YmZ1xp7jp42BsX1C+L8LOc+wE/LBLytuM/8uTMwNyrGM1S4G4gmu0mjrfYhMHI2A/35DLGv0b2lyL1OP39vGXX6uJUpv5zgorBOqjKGoxjly69rDss5q+qJziQ=
  - secure: aZAcVkVD5HypZPhUINNaVdr3ONhyaxl45kc5985hq1gWLoTFf/XGcY5+3cpYEEd+Oa9ushagKHaZjAw4/ZiLgIq+71HSyCRkbMAAzKunFWFbhejNpAom9Z0ID7ER0Xt0Y0J4XSkcJBFw9lcD7VCMQcmuEMEd+vkrRBnfU2hubGQEpjgzfNeY1Ey3WrDNiuhB3cMo/PKiF3krNh+zdPqQv8UkR1TmDRYBEfsNgsVb6/yT3BPDkSRNHIyBqdMJEf5leC7yJa/NecP8xJb8wR31avzWjEhK0pzt7u+Zt5RjbA6lZp97JTvKUDPhbcJa+eWOg9Qpu8UFRkHdyddarCooPfm7uxuVSg7FeOy0DvUsw27mg8PjklayaVwOHdL5Dc4lrECcxrhOH+FwE0+rrxfQuK14GVOhosdpLTtr43je9oVJyf3UmgIaLPpycpVinga3sj7P4q6Y3Aiofc1DERS66AcW1ZLeuCJaDmPsHx3CIU31916nSUTyBJHyUcTvt6LG0aK8uPh9arT94xlmltQHk9ZaskCFnegIlOrotMF31e3/iA/XX83H7knKE0ZpAlwzDpGmBBFgLGKm9Z7/CHUNE751WlflghIekWT58UwvzyCas1Dd02Fn9Ss4G0WKyjK1mm3NwYU+mYpsHI69d5oXpoYT8BCHr9ul7yZEx/duj5A=
  - secure: WDYiJjM8RiNNgA1DKX0NntJvW0WX/9lKPtHKrJPLf8iy5/vWrjruUwD87FSuFXy/QiJifFVik+XnTcF2WVDfJQNwGvUtbRQAl+b4rP5uabwIMyMfF0+UN3SQU7aQRPPAxcp2FtdB7y4kKX7yjZmoVnk8C665jFNWD8Bpc48Avs0BlDkqXUTC1eStN0jM9oJn+rOcTcnGzwpAsq+LnRTLFv5ubHAewZqfqCDUSPcYe9N68V1bMswzOia9mmbC2WQc1AYn4WCjdhaxb92VbegrdI7z8Gl7F4PFE3ElKV3YNWaIXrV57NIxpD1cd5ICCl+ozb7bkW5LgDdXd0RIFgeG6gxzFxqI5XfOGhFtOhw8KD6KskPVhczmSTEWAhjMva0qa3rw9LtIbKzd1FWXbMsPvXMpgSWfYgAXSTG0a98LjBvYg9LhUS1cLFRhMOx1yvOM+NxkfAENdcRPGE7uZhoXXr4rkbS/gmHi4lJqVk3l69pTsPVGciMxQG9eue25Qrw3OFxm/Z5S/SvKfi9I5yPMuqxzQh/1IrE1Gu+hkPLrkxGYktvwUqlXUV2ewUTxY6eJ38A+JrUvCZGOa+Gwt0I/dNVmNrUr3p4gurOkyYQcC7gnufbtAkQfFzOsWR77NOOx1nVpRAb7oZy9csTB9Sgf3VMHzzu1WL4Dj8WPKqFMd84=
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_eae7d3ca500f_key -iv $encrypted_eae7d3ca500f_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
