language: ruby
rvm:
- 2.4
install:
- gem install jekyll
- bundle install
- bundle update jekyll
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
  - bundle exec jekyll build
