language: ruby
rvm:
- 2.4
install:
- gem install jekyll
- gem install jekyll-redirect-from
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: HQbG/PE9NLqW0yBJJHoE5khVn55EioC8Xa8nZ+l4eUJX7c0eIw/ow7yn4/2Al+tsvb/YRToAZKd2P59F7a5zUlctvC04VEkhwLcyRGjLJB9byvXkKiJKfwrrTsNNZgCyrCWnMIipiKL94x7S+Jb5P4zXloSvRY6gEwh1JofmsrsAJ4SHyz3jj0LtCzu7gllBxMLWGTWCLwiRdZokCaoRfWWIKc3F6JV59LNXV9mc8ifCN4sZ8rSi7rnIwvYKMeazotLA+vDxXUGQpXUdoxOLjcGdEMszyILtY58gFOHhX5WQ1sVSJ27/smwcOGjHr+iAE9qVt9QDkr7l5lBn2IMUBEm62IEDWE63HpBI/pRKqs8i3XZGJw7MINMNUpIzQ8DxiHMmneJD6st+wV03AWob/bmX8Tdr7QcBbtq9XGMBnpJuLqEBbuQuMPDSzg7kV6D31ykUq9mg49rMoztUebt9mM/WZnqnjnscvounkYjYqiHjeiIQ85rLtb1wfRQy7eBSNwnlp7kyYn+6+vk0xMWoOgRLlHzphDrssN7K9+jv9epp9OXl1fciC+Qr3KJfSAgn9F1AhDvVFiVwokfZVw9edm+6Ww3v0qeGmUyg7aAX1P7D1rjIjwHRytgjwVnRknPuYQzRnAgvmzGl4jeb9/Z+rTSoi4LSwST3NsQj+BlBT7Q=
  - secure: NyupI/6g5mKRTFDzgGSXiDdRZtxSXX+tbrtWmlv9gzkCodHHtHegDqRb873uxE3b9rnXOgRoYWNHubNVGavz54Q+YZALAtvPhKWnrbWkZ7HzefutLDoREi9F3jwLb/wYNXw8GOZQx11bDa0v/3bLh9yd3HsuR2sGtZWhfwpSdJAnVq8KIEL0mgqw9Yfj9S3WP7JjleU50CAqjopD3WABldS05QbB5UhJz0wcaAjniYgJ+MASjTqT3FGYJFWp2urakokslSY/QuL+xS9iBVfUAjbXaoHga9dg7zaemYBQZ5s4nIVxxTp6k774LpjuJbIBTQW/WnxxDf35QnS3bnTRYbBj5cFzlUnsbxRGySBmQC1zMqJLEKMjZ4hNtzyTMSFx0gMAWpefNT6cu/vK9zU3AlKXiqMv8cFaLVRMqvUIhf5hf6aDYefublmCZEcvN3s/5/J1XU85B/B9qLIemHXxOXbTFfw06Rb8Opa0bE8PPar5eKQP9YFF0M6wiNSWuG3HsoaV+udsTBqJOyPqPlPWhTnvTz1e1RWIJ9m0AvL6wQZSxsuTqxIY726ciBt8rIbnGqglPIr11nJ0mm7MNdZCxZSB8P3aLWUOLZ9fueP3VLSsqyYtJN+asUrY5WRE6Dm0KC9HDsCfEoPwI9GxYXqGnp12J41euiv9B/oOoCZ9sRM=
  - secure: mtWfrpdZuRtwlwnu+X1OSGIrqWDLMXiKcS8+d7oFfLdwoC2yGKA18bsx4gQ8dZRUFAnxSJsQXZwLO6Op+6UAlftGnCAhtWnvf+w7WKLbfR/gW7QQadIXPNGelQbFjpWiEdrWWQJSV3wG7JvnbiSoQ0w5ltH2MrXGBrBmA+EAJJBEYdVMyFGZB1lzePeQjZ2ZEsySBazjwK7PrR5FLlMi2vAO+fs8Iwi5Zyou2y+smjmAOHqd+A3TM1o2BCXM+G5OD9LPJD0SALyPy6H4NoGnc4u5iriU2MBzImpznwr5JAOV0KbWs7swpq+TFCZ4WSM12b1T9WB94eSIu6vuoADbYKo99tLPvoCl4CoBnyH0EqW5A5cTIUfv4J61sF3qjBaIqMVj6b1cMxiqHClH5YjcuLALVPESVFYmeacINQ2SFBsBDNftUmBYKXlc7Yhyf85JFR90VrR/RRIKKzgOVVz0fAXArr59m1jL9ioKknud3eU2uvMgMLpA4pdxjiutO82bfTS6hXCSMe4v5JZDAf5+gSGsH6UiQEDmzaFqYnM7hI0iBR+PoHGKVfH/oR8m14SMSyrsFC1eInG7gcJwT7roHP4ZLTeP5HlbLyc5IW/Paj4E9LChvRgsTuhQkNIMpCYsx14wV7oFTHRmrQ75EnHU/9r8rt7BS0ilUCEniYxB1qw=
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_eae7d3ca500f_key -iv $encrypted_eae7d3ca500f_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
    branch: draft
