language: ruby
rvm:
- 2.4
install:
- gem install jekyll
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: PLc/x3+pMQGYrjJ5BY7l/lHWHBmQlvavrCAQRfhElcqsGCoYhv2wgqroThsbZ0nKtKaF14+EI0/p5IGDe6iGkc+OqF39Hbq7cFcbVgTfqYm3u5MZ4VTxNVg2F/YoJuTFvZ88RSOUFNIlzZcop2E+njPyxBTr3SoJFm1hTkkx2hCX93R6uIxKrExVllg64sw6f1TAueDmwus+luONsY5bC0RBPjxOuegqGJvT3I/YqxIkpme1YaSSa1aio5ml4h4nZhOW7DWwGVMoijBqcTtXphM5QN6ZFbO5q0KnmGE+mjrQhgz32/BXPUzVLvTaCRG8KjGco81tWSa6E07njbRna0OIGr3xYfUqmvf0OnbdYy+LICJTFYxvPfxNbCrBGFdIiehdEXXIHaehOFF4OwwbQSvAZ6WlJhMX90DC9fKSE3yoKOHaBbLjnm20vusHZEjltCIPc2mnqOt1AsbwlsGwuC+HK82NUTt2B4Z0t1EyeWLBLdxzZpgzPrZHoYWlj5PNVvymGTTqqIZ1sd0VoAGSnLMC9dM/vupX9ummGKdLpz44n+2q4GltSXHizh3u8zEHgTPp2t/IbX+mDxmVWJoFY8a69JGLocni+CQTSZrKTQIzuAsG5jguaQP741MGOm0oDdmIIDqn5HGjKl//sxKUYvG+zRzFCOfdzhAd655474o=
  - secure: MMlcUKRrq5Cqevt9s7PPHHt7ZSSVBsYQnUqe4dsUfGsTCI0hSmYO4mBRa72c704I1XSpT7du4REOvxTAMo55H48rxBs3n8fpLERvamUzaxTZoWbusZ1BpTvTvYC4FJ5dAR9e6ejLT21W0om571P0snUAsSc1rzSFrmnc8uFG8mmAA1bwtTX0ABL9wIoVbvGJQNuVYdCXi8TnYVT0JdcEHeAHl3U4G3ZEzqeTwnoM0AAR3HMrk2ap7GrXMzfegM1CjxQyNy5yBy1cPku7tlQf+ivuY65UIUpgmHu/xCawbkXHWgzjLFndWlclX0DLuICPpbfo6WXhrhTnpq91Og4cgg4brS1h4ku2ILyUiqm66zgbG8rwEI3esX22ouNmTOaCSXQZeroA/JGoEONp0m5nl1Kn+86/d5LH/8NukgY5kvJ57S3yIY0xy/eEHDPL7ic7mnOLK/17d0xmhxS5u+MTo4UGubanBbDqaFDepzQuK1GQ+/tFtwq8UfSNYaMfH1o8AV5GndSKRyNBu4jJ7Y29r33XHjXhbjXiPR2CWn71OgU7WrLEOXpeREKvNuxrqYl/ZoGRo1lxff9hmsfTe1QIEU8N0Ltkz/SAqZS6v1Oyvpwmjt+Fk4qfm0hiRQgkPBpSl4XV7Gu8oJY/Jo76CXzfEA5U5h7DzuEgGzVuBo2oaNQ=
  - secure: 1FF1ybwbsJQ3xPGH/lIcy55zVg+OGLQ8s/FXeTDtKToPBrosUZKju615ffCAiMBtAdoJPRvVyyWBg3w9EYe0DuuHrzqgA67SNR20RBcAMHLWWge+7Wqm86D9pz84Uobhr1UNDZy8GmnnKKi24qWsvR742/XOj6dZfstVGQx+FhFM3pHaM6XfR1iNskQli+I0GG9CFFbgTt4M6tK/V8HZRIyusRWMxjAdhNczfMLZDptt8LSavIXCYk+DonamNNecXUFSOu/w0gz0ewteePp6G3KBG5TalAA4XYrmZv2pZts4V9QsbHdjBiUTqgI1alFCyvMfyX3OnHnqyvda0lckNtWQFHdaOriDogQWO+ttjkAJ66qfcctsyGHj02MLJQgK1tV6f6gg4HC9FUI31Nk88tdYvndpgFwo1adbhPinbA9V66WVyCwN/b6ohKw8X0wx4xd/bCILCFrB/fw3lVFC+pq7oqJLuoAyCVRITMObLYifX2EkzH5PrCL8JrPcTxxXPsbcPXZDdQJvT5mogzNwh4dzH8VQk/0n/j4+0w/vdCd/YP7QDDlCdTU9uD+weD30g9zYo6Wyk0Jp/kCJcgBaugEZ3l090g3LHxS/qSzKyqQgU5+K2nU+3qPybadB9urJ1HlUMva3+79oD4TuuRD9SljwciTDsccLVVPY5kmDeJY=
script:
- bundle exec jekyll build
before_deploy:
- openssl aes-256-cbc -K $encrypted_e918b92733bd_key -iv $encrypted_e918b92733bd_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- ssh-add /tmp/deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master