# Blog settings
permalink: /blog/:year/:title
baseurl: "http://nilsreiter.de"

title: nilsreiter.de
author:
  name: Nils Reiter
  email: nils.reiter@ims.uni-stuttgart.de


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

collections:
  publications:
    output: true
