# Blog settings
permalink: /blog/:year/:title
url: "https://nilsreiter.de"
description: "General information, blog, publications, cv of Nils Reiter"

title: nilsreiter.de
author:
  name: Nils Reiter
  email: nils.reiter@ims.uni-stuttgart.de
keywords:
- DH
- Digital Humanities
- Stuttgart
- NLP
- Natural Language Processing
- science
- scientist


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

collections:
  publications:
    output: true

kramdown:
  auto_ids: true

plugins:
- jekyll-redirect-from