# Blog settings
permalink: /blog/:title


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

collections:
  publications:
    output: true
