name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🛎 Check out master
      uses: actions/checkout@master
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle Install
      run: |
        sudo gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: 🔨 Build site
      run: bundle exec jekyll build
    - name: 🧪 deploy
      run: bash deploy.sh
      env: # Or as an environment variable
        DEPLOY_DIRECTORY: ${{ secrets.DEPLOY_DIRECTORY }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
